name: Rafiq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  http: ^1.6.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  icons_plus:
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  

  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/iconn.png"

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
  assets:
    - assets/image/
    - assets/animations/
